export default [
    {key: 'ab', title: 'Abkhaze', originalTitle: 'аҧсуа'},
    {key: 'aa', title: 'Afar', originalTitle: 'Afaraf'},
    {key: 'af', title: 'Afrikaans', originalTitle: 'Afrikaans'},
    {key: 'ak', title: 'Akan', originalTitle: 'Akan'},
    {key: 'sq', title: 'Albanais', originalTitle: 'Shqip'},
    {key: 'am', title: 'Amharique', originalTitle: 'አማርኛ'},
    {key: 'ar', title: 'Arabe', originalTitle: 'العربية'},
    {key: 'an', title: 'Aragonais', originalTitle: 'Aragonés'},
    {key: 'hy', title: 'Arménien', originalTitle: 'Հայերեն'},
    {key: 'as', title: 'Assamais', originalTitle: 'অসমীয়া'},
    {key: 'av', title: 'Avar', originalTitle: 'авар мацӀ, магӀарул мацӀ'},
    {key: 'ae', title: 'Avestique', originalTitle: 'Avesta'},
    {key: 'ay', title: 'Aymara', originalTitle: 'Aymar aru'},
    {key: 'az', title: 'Azerbaïdjanais', originalTitle: 'azərbaycan dili'},
    {key: 'bm', title: 'Bambara', originalTitle: 'bamanankan'},
    {key: 'ba', title: 'Bachkir', originalTitle: 'башҡорт теле'},
    {key: 'eu', title: 'Basque', originalTitle: 'euskara, euskera'},
    {key: 'be', title: 'Biélorusse', originalTitle: 'Беларуская'},
    {key: 'bn', title: 'Bengali', originalTitle: 'বাংলা'},
    {key: 'bh', title: 'Bihari', originalTitle: 'भोजपुरी'},
    {key: 'bi', title: 'Bislama', originalTitle: 'Bislama'},
    {key: 'bs', title: 'Bosnien', originalTitle: 'Bosanski jezik'},
    {key: 'br', title: 'Breton', originalTitle: 'brezhoneg'},
    {key: 'bg', title: 'Bulgare', originalTitle: 'български език'},
    {key: 'my', title: 'Birman', originalTitle: 'ဗမာစာ'},
    {key: 'ca', title: 'Catalan', originalTitle: 'Català'},
    {key: 'ch', title: 'Chamorro', originalTitle: 'Chamoru'},
    {key: 'ce', title: 'Chechen', originalTitle: 'нохчийн мотт'},
    {key: 'ny', title: 'Chichewa', originalTitle: 'chiCheŵa, chinyanja'},
    {key: 'zh', title: 'Chinois', originalTitle: '中文 (Zhōngwén), 汉语, 漢語'},
    {key: 'cv', title: 'Tchouvache', originalTitle: 'чӑваш чӗлхи'},
    {key: 'kw', title: 'Cornique', originalTitle: 'Kernewek'},
    {key: 'co', title: 'Corse', originalTitle: 'corsu, lingua corsa'},
    {key: 'cr', title: 'Cree', originalTitle: 'ᓀᐦᐃᔭᐍᐏᐣ'},
    {key: 'hr', title: 'Croate', originalTitle: 'hrvatski'},
    {key: 'cs', title: 'Tchèque', originalTitle: 'česky, čeština'},
    {key: 'da', title: 'Danois', originalTitle: 'dansk'},
    {key: 'dv', title: 'Divehi', originalTitle: 'ދިވެހި'},
    {key: 'nl', title: 'Néerlandais', originalTitle: 'Nederlands, Vlaams'},
    {key: 'en', title: 'Anglais', originalTitle: 'English'},
    {key: 'eo', title: 'Espéranto', originalTitle: 'Esperanto'},
    {key: 'et', title: 'Estonien', originalTitle: 'eesti, eesti keel'},
    {key: 'ee', title: 'Éwé', originalTitle: 'Eʋegbe'},
    {key: 'fo', title: 'Féroïen', originalTitle: 'føroyskt'},
    {key: 'fj', title: 'Fidjien', originalTitle: 'vosa Vakaviti'},
    {key: 'fi', title: 'Finnois', originalTitle: 'suomi, suomen kieli'},
    {key: 'fr', title: 'Français', originalTitle: 'Français'},
    {key: 'ff', title: 'Peul', originalTitle: 'Fulfulde, Pulaar, Pular'},
    {key: 'gl', title: 'Galicien', originalTitle: 'Galego'},
    {key: 'ka', title: 'Géorgien', originalTitle: 'ქართული'},
    {key: 'de', title: 'Allemand', originalTitle: 'Deutsch'},
    {key: 'el', title: 'Grec moderne', originalTitle: 'Ελληνικά'},
    {key: 'gn', title: 'Guarani', originalTitle: 'Avañeẽ'},
    {key: 'gu', title: 'Gujarati', originalTitle: 'ગુજરાતી'},
    {key: 'ht', title: 'Créole haïtien', originalTitle: 'Kreyòl ayisyen'},
    {key: 'ha', title: 'Haoussa', originalTitle: 'Hausa, هَوُسَ'},
    {key: 'he', title: 'Hébreu', originalTitle: 'עברית'},
    {key: 'hz', title: 'Héréro', originalTitle: 'Otjiherero'},
    {key: 'hi', title: 'Hindi', originalTitle: 'हिन्दी, हिंदी'},
    {key: 'ho', title: 'Hiri Motu', originalTitle: 'Hiri Motu'},
    {key: 'hu', title: 'Hongrois', originalTitle: 'Magyar'},
    {key: 'ia', title: 'Interlingua', originalTitle: 'Interlingua'},
    {key: 'id', title: 'Indonésien', originalTitle: 'Bahasa Indonesia'},
    {key: 'ie', title: 'Interlingue', originalTitle: 'Originally called Occidental; then Interlingue after WWII'},
    {key: 'ga', title: 'Irlandais', originalTitle: 'Gaeilge'},
    {key: 'ig', title: 'Igbo', originalTitle: 'Asụsụ Igbo'},
    {key: 'ik', title: 'Inupiaq', originalTitle: 'Iñupiaq, Iñupiatun'},
    {key: 'io', title: 'Ido', originalTitle: 'Ido'},
    {key: 'is', title: 'Islandais', originalTitle: 'Íslenska'},
    {key: 'it', title: 'Italien', originalTitle: 'Italiano'},
    {key: 'iu', title: 'Inuktitut', originalTitle: 'ᐃᓄᒃᑎᑐᑦ'},
    {key: 'ja', title: 'Japonais', originalTitle: '日本語 (にほんご／にっぽんご)'},
    {key: 'jv', title: 'Javanais', originalTitle: 'basa Jawa'},
    {key: 'kl', title: 'Groenlandais', originalTitle: 'kalaallisut, kalaallit oqaasii'},
    {key: 'kn', title: 'Kannada', originalTitle: 'ಕನ್ನಡ'},
    {key: 'kr', title: 'Kanouri', originalTitle: 'Kanuri'},
    {key: 'ks', title: 'Kashmiri', originalTitle: 'कश्मीरी, كشميري‎'},
    {key: 'kk', title: 'Kazakh', originalTitle: 'Қазақ тілі'},
    {key: 'km', title: 'Khmer', originalTitle: 'ភាសាខ្មែរ'},
    {key: 'ki', title: 'Kikuyu', originalTitle: 'Gĩkũyũ'},
    {key: 'rw', title: 'Kinyarwanda', originalTitle: 'Ikinyarwanda'},
    {key: 'ky', title: 'Kirghize', originalTitle: 'кыргыз тили'},
    {key: 'kv', title: 'Komi', originalTitle: 'коми кыв'},
    {key: 'kg', title: 'Kongo', originalTitle: 'KiKongo'},
    {key: 'ko', title: 'Coréen', originalTitle: '한국어 (韓國語), 조선말 (朝鮮語)'},
    {key: 'ku', title: 'Kurde', originalTitle: 'Kurdî, كوردی‎'},
    {key: 'kj', title: 'Kwanyama', originalTitle: 'Kuanyama'},
    {key: 'la', title: 'Latin', originalTitle: 'latine, lingua latina'},
    {key: 'lb', title: 'Luxembourgeois', originalTitle: 'Lëtzebuergesch'},
    {key: 'lg', title: 'Ganda', originalTitle: 'Luganda'},
    {key: 'li', title: 'Limbourgeois', originalTitle: 'Limburgs'},
    {key: 'ln', title: 'Lingala', originalTitle: 'Lingála'},
    {key: 'lo', title: 'Lao', originalTitle: 'ພາສາລາວ'},
    {key: 'lt', title: 'Lituanien', originalTitle: 'lietuvių kalba'},
    {key: 'lu', title: 'Luba-Katanga', originalTitle: ''},
    {key: 'lv', title: 'Letton', originalTitle: 'latviešu valoda'},
    {key: 'gv', title: 'Mannois', originalTitle: 'Gaelg, Gailck'},
    {key: 'mk', title: 'Macédonien', originalTitle: 'македонски јазик'},
    {key: 'mg', title: 'Malgache', originalTitle: 'Malagasy fiteny'},
    {key: 'ms', title: 'Malais', originalTitle: 'bahasa Melayu, بهاس ملايو‎'},
    {key: 'ml', title: 'Malayalam', originalTitle: 'മലയാളം'},
    {key: 'mt', title: 'Maltais', originalTitle: 'Malti'},
    {key: 'mi', title: 'Maori', originalTitle: 'te reo Māori'},
    {key: 'mr', title: 'Marathi', originalTitle: 'मराठी'},
    {key: 'mh', title: 'Marshallais', originalTitle: 'Kajin M̧ajeļ'},
    {key: 'mn', title: 'Mongol', originalTitle: 'монгол'},
    {key: 'na', title: 'Nauruan', originalTitle: 'Ekakairũ Naoero'},
    {key: 'nv', title: 'Navajo', originalTitle: 'Diné bizaad, Dinékʼehǰí'},
    {key: 'nb', title: 'Norvégien Bokmål', originalTitle: 'Norsk bokmål'},
    {key: 'nd', title: 'Ndebele du Nord', originalTitle: 'isiNdebele'},
    {key: 'ne', title: 'Népalais', originalTitle: 'नेपाली'},
    {key: 'ng', title: 'Ndonga', originalTitle: 'Owambo'},
    {key: 'nn', title: 'Norvégien Nynorsk', originalTitle: 'Norsk nynorsk'},
    {key: 'no', title: 'Norvégien', originalTitle: 'Norsk'},
    {key: 'ii', title: 'Yi de Sichuan', originalTitle: 'ꆈꌠ꒿ Nuosuhxop'},
    {key: 'nr', title: 'Ndebele du Sud', originalTitle: 'isiNdebele'},
    {key: 'oc', title: 'Occitan', originalTitle: 'Occitan'},
    {key: 'oj', title: 'Ojibwé', originalTitle: 'ᐊᓂᔑᓈᐯᒧᐎᓐ'},
    {key: 'cu', title: 'Vieux-slave', originalTitle: 'ѩзыкъ словѣньскъ'},
    {key: 'om', title: 'Oromo', originalTitle: 'Afaan Oromoo'},
    {key: 'or', title: 'Oriya', originalTitle: 'ଓଡ଼ିଆ'},
    {key: 'os', title: 'Ossète', originalTitle: 'ирон æвзаг'},
    {key: 'pa', title: 'Pendjabi', originalTitle: 'ਪੰਜਾਬੀ, پنجابی‎'},
    {key: 'pi', title: 'Pali', originalTitle: 'पाऴि'},
    {key: 'fa', title: 'Persan', originalTitle: 'فارسی'},
    {key: 'pl', title: 'Polonais', originalTitle: 'polski'},
    {key: 'ps', title: 'Pachto', originalTitle: 'پښتو'},
    {key: 'pt', title: 'Portugais', originalTitle: 'Português'},
    {key: 'qu', title: 'Quechua', originalTitle: 'Runa Simi, Kichwa'},
    {key: 'rm', title: 'Romanche', originalTitle: 'rumantsch grischun'},
    {key: 'rn', title: 'Rundi', originalTitle: 'kiRundi'},
    {key: 'ro', title: 'Roumain', originalTitle: 'română'},
    {key: 'ru', title: 'Russe', originalTitle: 'русский язык'},
    {key: 'sa', title: 'Sanskrit', originalTitle: 'संस्कृतम्'},
    {key: 'sc', title: 'Sarde', originalTitle: 'sardu'},
    {key: 'sd', title: 'Sindhi', originalTitle: 'सिन्धी, سنڌي، سندھی‎'},
    {key: 'se', title: 'Sami du Nord', originalTitle: 'Davvisámegiella'},
    {key: 'sm', title: 'Samoan', originalTitle: 'gagana faa Samoa'},
    {key: 'sg', title: 'Sango', originalTitle: 'yângâ tî sängö'},
    {key: 'sr', title: 'Serbe', originalTitle: 'српски језик'},
    {key: 'gd', title: 'Gaélique écossais', originalTitle: 'Gàidhlig'},
    {key: 'sn', title: 'Shona', originalTitle: 'chiShona'},
    {key: 'si', title: 'Cinghalais', originalTitle: 'සිංහල'},
    {key: 'sk', title: 'Slovaque', originalTitle: 'slovenčina'},
    {key: 'sl', title: 'Slovène', originalTitle: 'slovenščina'},
    {key: 'so', title: 'Somali', originalTitle: 'Soomaaliga, af Soomaali'},
    {key: 'st', title: 'Sotho du Sud', originalTitle: 'Sesotho'},
    {key: 'es', title: 'Espagnol', originalTitle: 'español, castellano'},
    {key: 'su', title: 'Soundanais', originalTitle: 'Basa Sunda'},
    {key: 'sw', title: 'Swahili', originalTitle: 'Kiswahili'},
    {key: 'ss', title: 'Swati', originalTitle: 'SiSwati'},
    {key: 'sv', title: 'Suédois', originalTitle: 'svenska'},
    {key: 'ta', title: 'Tamoul', originalTitle: 'தமிழ்'},
    {key: 'te', title: 'Télougou', originalTitle: 'తెలుగు'},
    {key: 'tg', title: 'Tadjik', originalTitle: 'тоҷикӣ, toğikī, تاجیکی‎'},
    {key: 'th', title: 'Thaï', originalTitle: 'ไทย'},
    {key: 'ti', title: 'Tigrinya', originalTitle: 'ትግርኛ'},
    {key: 'bo', title: 'Tibétain standard', originalTitle: 'བོད་ཡིག'},
    {key: 'tk', title: 'Turkmène', originalTitle: 'Türkmen, Түркмен'},
    {key: 'tl', title: 'Tagalog', originalTitle: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔'},
    {key: 'tn', title: 'Tswana', originalTitle: 'Setswana'},
    {key: 'to', title: 'Tongien', originalTitle: 'faka Tonga'},
    {key: 'tr', title: 'Turc', originalTitle: 'Türkçe'},
    {key: 'ts', title: 'Tsonga', originalTitle: 'Xitsonga'},
    {key: 'tt', title: 'Tatar', originalTitle: 'татарча, tatarça, تاتارچا‎'},
    {key: 'tw', title: 'Twi', originalTitle: 'Twi'},
    {key: 'ty', title: 'Tahitien', originalTitle: 'Reo Tahiti'},
    {key: 'ug', title: 'Ouïghour', originalTitle: 'Uyƣurqə, ئۇيغۇرچە‎'},
    {key: 'uk', title: 'Ukrainien', originalTitle: 'українська'},
    {key: 'ur', title: 'Ourdou', originalTitle: 'اردو'},
    {key: 'uz', title: 'Ouzbek', originalTitle: 'zbek, Ўзбек, أۇزبېك‎'},
    {key: 've', title: 'Venda', originalTitle: 'Tshivenḓa'},
    {key: 'vi', title: 'Vietnamien', originalTitle: 'Tiếng Việt'},
    {key: 'vo', title: 'Volapük', originalTitle: 'Volapük'},
    {key: 'wa', title: 'Wallon', originalTitle: 'Walon'},
    {key: 'cy', title: 'Gallois', originalTitle: 'Cymraeg'},
    {key: 'wo', title: 'Wolof', originalTitle: 'Wollof'},
    {key: 'fy', title: 'Frison occidental', originalTitle: 'Frysk'},
    {key: 'xh', title: 'Xhosa', originalTitle: 'isiXhosa'},
    {key: 'yi', title: 'Yiddish', originalTitle: 'ייִדיש'},
    {key: 'yo', title: 'Yoruba', originalTitle: 'Yorùbá'},
    {key: 'za', title: 'Zhuang', originalTitle: 'Saɯ cueŋƅ, Saw cuengh'},
  ];