export default [
    {key: 'ab', title: 'Abkhaz', originalTitle: 'аҧсуа'},
    {key: 'aa', title: 'Afar', originalTitle: 'Afaraf'},
    {key: 'af', title: 'Afrikaans', originalTitle: 'Afrikaans'},
    {key: 'ak', title: 'Akan', originalTitle: 'Akan'},
    {key: 'sq', title: 'Albanian', originalTitle: 'Shqip'},
    {key: 'am', title: 'Amharic', originalTitle: 'አማርኛ'},
    {key: 'ar', title: 'Arabic', originalTitle: 'العربية'},
    {key: 'an', title: 'Aragonese', originalTitle: 'Aragonés'},
    {key: 'hy', title: 'Armenian', originalTitle: 'Հայերեն'},
    {key: 'as', title: 'Assamese', originalTitle: 'অসমীয়া'},
    {key: 'av', title: 'Avaric', originalTitle: 'авар мацӀ, магӀарул мацӀ'},
    {key: 'ae', title: 'Avestan', originalTitle: 'Avesta'},
    {key: 'ay', title: 'Aymara', originalTitle: 'Aymar aru'},
    {key: 'az', title: 'Azerbaijani', originalTitle: 'azərbaycan dili'},
    {key: 'bm', title: 'Bambara', originalTitle: 'bamanankan'},
    {key: 'ba', title: 'Bashkir', originalTitle: 'башҡорт теле'},
    {key: 'eu', title: 'Basque', originalTitle: 'euskara, euskera'},
    {key: 'be', title: 'Belarusian', originalTitle: 'Беларуская'},
    {key: 'bn', title: 'Bengali', originalTitle: 'বাংলা'},
    {key: 'bh', title: 'Bihari', originalTitle: 'भोजपुरी'},
    {key: 'bi', title: 'Bislama', originalTitle: 'Bislama'},
    {key: 'bs', title: 'Bosnian', originalTitle: 'Bosanski jezik'},
    {key: 'br', title: 'Breton', originalTitle: 'brezhoneg'},
    {key: 'bg', title: 'Bulgarian', originalTitle: 'български език'},
    {key: 'my', title: 'Burmese', originalTitle: 'ဗမာစာ'},
    {key: 'ca', title: 'Catalan', originalTitle: 'Català'},
    {key: 'ch', title: 'Chamorro', originalTitle: 'Chamoru'},
    {key: 'ce', title: 'Chechen', originalTitle: 'нохчийн мотт'},
    {key: 'ny', title: 'Chichewa', originalTitle: 'chiCheŵa, chinyanja'},
    {key: 'zh', title: 'Chinese', originalTitle: '中文 (Zhōngwén), 汉语, 漢語'},
    {key: 'cv', title: 'Chuvash', originalTitle: 'чӑваш чӗлхи'},
    {key: 'kw', title: 'Cornish', originalTitle: 'Kernewek'},
    {key: 'co', title: 'Corsican', originalTitle: 'corsu, lingua corsa'},
    {key: 'cr', title: 'Cree', originalTitle: 'ᓀᐦᐃᔭᐍᐏᐣ'},
    {key: 'hr', title: 'Croatian', originalTitle: 'hrvatski'},
    {key: 'cs', title: 'Czech', originalTitle: 'česky, čeština'},
    {key: 'da', title: 'Danish', originalTitle: 'dansk'},
    {key: 'dv', title: 'Divehi', originalTitle: 'ދިވެހި'},
    {key: 'nl', title: 'Dutch', originalTitle: 'Nederlands, Vlaams'},
    {key: 'en', title: 'English', originalTitle: 'English'},
    {key: 'eo', title: 'Esperanto', originalTitle: 'Esperanto'},
    {key: 'et', title: 'Estonian', originalTitle: 'eesti, eesti keel'},
    {key: 'ee', title: 'Ewe', originalTitle: 'Eʋegbe'},
    {key: 'fo', title: 'Faroese', originalTitle: 'føroyskt'},
    {key: 'fj', title: 'Fijian', originalTitle: 'vosa Vakaviti'},
    {key: 'fi', title: 'Finnish', originalTitle: 'suomi, suomen kieli'},
    {key: 'fr', title: 'French', originalTitle: 'Français'},
    {key: 'ff', title: 'Fula', originalTitle: 'Fulfulde, Pulaar, Pular'},
    {key: 'gl', title: 'Galician', originalTitle: 'Galego'},
    {key: 'ka', title: 'Georgian', originalTitle: 'ქართული'},
    {key: 'de', title: 'German', originalTitle: 'Deutsch'},
    {key: 'el', title: 'Greek, Modern', originalTitle: 'Ελληνικά'},
    {key: 'gn', title: 'Guaraní', originalTitle: 'Avañeẽ'},
    {key: 'gu', title: 'Gujarati', originalTitle: 'ગુજરાતી'},
    {key: 'ht', title: 'Haitian', originalTitle: 'Kreyòl ayisyen'},
    {key: 'ha', title: 'Hausa', originalTitle: 'Hausa, هَوُسَ'},
    {key: 'he', title: 'Hebrew (modern)', originalTitle: 'עברית'},
    {key: 'hz', title: 'Herero', originalTitle: 'Otjiherero'},
    {key: 'hi', title: 'Hindi', originalTitle: 'हिन्दी, हिंदी'},
    {key: 'ho', title: 'Hiri Motu', originalTitle: 'Hiri Motu'},
    {key: 'hu', title: 'Hungarian', originalTitle: 'Magyar'},
    {key: 'ia', title: 'Interlingua', originalTitle: 'Interlingua'},
    {key: 'id', title: 'Indonesian', originalTitle: 'Bahasa Indonesia'},
    {key: 'ie', title: 'Interlingue', originalTitle: 'Originally called Occidental; then Interlingue after WWII'},
    {key: 'ga', title: 'Irish', originalTitle: 'Gaeilge'},
    {key: 'ig', title: 'Igbo', originalTitle: 'Asụsụ Igbo'},
    {key: 'ik', title: 'Inupiaq', originalTitle: 'Iñupiaq, Iñupiatun'},
    {key: 'io', title: 'Ido', originalTitle: 'Ido'},
    {key: 'is', title: 'Icelandic', originalTitle: 'Íslenska'},
    {key: 'it', title: 'Italian', originalTitle: 'Italiano'},
    {key: 'iu', title: 'Inuktitut', originalTitle: 'ᐃᓄᒃᑎᑐᑦ'},
    {key: 'ja', title: 'Japanese', originalTitle: '日本語 (にほんご／にっぽんご)'},
    {key: 'jv', title: 'Javanese', originalTitle: 'basa Jawa'},
    {key: 'kl', title: 'Kalaallisut', originalTitle: 'kalaallisut, kalaallit oqaasii'},
    {key: 'kn', title: 'Kannada', originalTitle: 'ಕನ್ನಡ'},
    {key: 'kr', title: 'Kanuri', originalTitle: 'Kanuri'},
    {key: 'ks', title: 'Kashmiri', originalTitle: 'कश्मीरी, كشميري‎'},
    {key: 'kk', title: 'Kazakh', originalTitle: 'Қазақ тілі'},
    {key: 'km', title: 'Khmer', originalTitle: 'ភាសាខ្មែរ'},
    {key: 'ki', title: 'Kikuyu', originalTitle: 'Gĩkũyũ'},
    {key: 'rw', title: 'Kinyarwanda', originalTitle: 'Ikinyarwanda'},
    {key: 'ky', title: 'Kirghiz', originalTitle: 'кыргыз тили'},
    {key: 'kv', title: 'Komi', originalTitle: 'коми кыв'},
    {key: 'kg', title: 'Kongo', originalTitle: 'KiKongo'},
    {key: 'ko', title: 'Korean', originalTitle: '한국어 (韓國語), 조선말 (朝鮮語)'},
    {key: 'ku', title: 'Kurdish', originalTitle: 'Kurdî, كوردی‎'},
    {key: 'kj', title: 'Kwanyama', originalTitle: 'Kuanyama'},
    {key: 'la', title: 'Latin', originalTitle: 'latine, lingua latina'},
    {key: 'lb', title: 'Luxembourgish', originalTitle: 'Lëtzebuergesch'},
    {key: 'lg', title: 'Luganda', originalTitle: 'Luganda'},
    {key: 'li', title: 'Limburgish', originalTitle: 'Limburgs'},
    {key: 'ln', title: 'Lingala', originalTitle: 'Lingála'},
    {key: 'lo', title: 'Lao', originalTitle: 'ພາສາລາວ'},
    {key: 'lt', title: 'Lithuanian', originalTitle: 'lietuvių kalba'},
    {key: 'lu', title: 'Luba-Katanga', originalTitle: ''},
    {key: 'lv', title: 'Latvian', originalTitle: 'latviešu valoda'},
    {key: 'gv', title: 'Manx', originalTitle: 'Gaelg, Gailck'},
    {key: 'mk', title: 'Macedonian', originalTitle: 'македонски јазик'},
    {key: 'mg', title: 'Malagasy', originalTitle: 'Malagasy fiteny'},
    {key: 'ms', title: 'Malay', originalTitle: 'bahasa Melayu, بهاس ملايو‎'},
    {key: 'ml', title: 'Malayalam', originalTitle: 'മലയാളം'},
    {key: 'mt', title: 'Maltese', originalTitle: 'Malti'},
    {key: 'mi', title: 'Māori', originalTitle: 'te reo Māori'},
    {key: 'mr', title: 'Marathi (Marāṭhī)', originalTitle: 'मराठी'},
    {key: 'mh', title: 'Marshallese', originalTitle: 'Kajin M̧ajeļ'},
    {key: 'mn', title: 'Mongolian', originalTitle: 'монгол'},
    {key: 'na', title: 'Nauru', originalTitle: 'Ekakairũ Naoero'},
    {key: 'nv', title: 'Navajo', originalTitle: 'Diné bizaad, Dinékʼehǰí'},
    {key: 'nb', title: 'Norwegian Bokmål', originalTitle: 'Norsk bokmål'},
    {key: 'nd', title: 'North Ndebele', originalTitle: 'isiNdebele'},
    {key: 'ne', title: 'Nepali', originalTitle: 'नेपाली'},
    {key: 'ng', title: 'Ndonga', originalTitle: 'Owambo'},
    {key: 'nn', title: 'Norwegian Nynorsk', originalTitle: 'Norsk nynorsk'},
    {key: 'no', title: 'Norwegian', originalTitle: 'Norsk'},
    {key: 'ii', title: 'Nuosu', originalTitle: 'ꆈꌠ꒿ Nuosuhxop'},
    {key: 'nr', title: 'South Ndebele', originalTitle: 'isiNdebele'},
    {key: 'oc', title: 'Occitan', originalTitle: 'Occitan'},
    {key: 'oj', title: 'Ojibwe, Ojibwa', originalTitle: 'ᐊᓂᔑᓈᐯᒧᐎᓐ'},
    {key: 'cu', title: 'Old Church Slavonic', originalTitle: 'ѩзыкъ словѣньскъ'},
    {key: 'om', title: 'Oromo', originalTitle: 'Afaan Oromoo'},
    {key: 'or', title: 'Oriya', originalTitle: 'ଓଡ଼ିଆ'},
    {key: 'os', title: 'Ossetian', originalTitle: 'ирон æвзаг'},
    {key: 'pa', title: 'Panjabi', originalTitle: 'ਪੰਜਾਬੀ, پنجابی‎'},
    {key: 'pi', title: 'Pāli', originalTitle: 'पाऴि'},
    {key: 'fa', title: 'Persian', originalTitle: 'فارسی'},
    {key: 'pl', title: 'Polish', originalTitle: 'polski'},
    {key: 'ps', title: 'Pashto', originalTitle: 'پښتو'},
    {key: 'pt', title: 'Portuguese', originalTitle: 'Português'},
    {key: 'qu', title: 'Quechua', originalTitle: 'Runa Simi, Kichwa'},
    {key: 'rm', title: 'Romansh', originalTitle: 'rumantsch grischun'},
    {key: 'rn', title: 'Kirundi', originalTitle: 'kiRundi'},
    {key: 'ro', title: 'Romanian', originalTitle: 'română'},
    {key: 'ru', title: 'Russian', originalTitle: 'русский язык'},
    {key: 'sa', title: 'Sanskrit (Saṁskṛta)', originalTitle: 'संस्कृतम्'},
    {key: 'sc', title: 'Sardinian', originalTitle: 'sardu'},
    {key: 'sd', title: 'Sindhi', originalTitle: 'सिन्धी, سنڌي، سندھی‎'},
    {key: 'se', title: 'Northern Sami', originalTitle: 'Davvisámegiella'},
    {key: 'sm', title: 'Samoan', originalTitle: 'gagana faa Samoa'},
    {key: 'sg', title: 'Sango', originalTitle: 'yângâ tî sängö'},
    {key: 'sr', title: 'Serbian', originalTitle: 'српски језик'},
    {key: 'gd', title: 'Scottish Gaelic', originalTitle: 'Gàidhlig'},
    {key: 'sn', title: 'Shona', originalTitle: 'chiShona'},
    {key: 'si', title: 'Sinhala, Sinhalese', originalTitle: 'සිංහල'},
    {key: 'sk', title: 'Slovak', originalTitle: 'slovenčina'},
    {key: 'sl', title: 'Slovene', originalTitle: 'slovenščina'},
    {key: 'so', title: 'Somali', originalTitle: 'Soomaaliga, af Soomaali'},
    {key: 'st', title: 'Southern Sotho', originalTitle: 'Sesotho'},
    {key: 'es', title: 'Spanish', originalTitle: 'español, castellano'},
    {key: 'su', title: 'Sundanese', originalTitle: 'Basa Sunda'},
    {key: 'sw', title: 'Swahili', originalTitle: 'Kiswahili'},
    {key: 'ss', title: 'Swati', originalTitle: 'SiSwati'},
    {key: 'sv', title: 'Swedish', originalTitle: 'svenska'},
    {key: 'ta', title: 'Tamil', originalTitle: 'தமிழ்'},
    {key: 'te', title: 'Telugu', originalTitle: 'తెలుగు'},
    {key: 'tg', title: 'Tajik', originalTitle: 'тоҷикӣ, toğikī, تاجیکی‎'},
    {key: 'th', title: 'Thai', originalTitle: 'ไทย'},
    {key: 'ti', title: 'Tigrinya', originalTitle: 'ትግርኛ'},
    {key: 'bo', title: 'Tibetan Standard', originalTitle: 'བོད་ཡིག'},
    {key: 'tk', title: 'Turkmen', originalTitle: 'Türkmen, Түркмен'},
    {key: 'tl', title: 'Tagalog', originalTitle: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔'},
    {key: 'tn', title: 'Tswana', originalTitle: 'Setswana'},
    {key: 'to', title: 'Tonga (Tonga Islands)', originalTitle: 'faka Tonga'},
    {key: 'tr', title: 'Turkish', originalTitle: 'Türkçe'},
    {key: 'ts', title: 'Tsonga', originalTitle: 'Xitsonga'},
    {key: 'tt', title: 'Tatar', originalTitle: 'татарча, tatarça, تاتارچا‎'},
    {key: 'tw', title: 'Twi', originalTitle: 'Twi'},
    {key: 'ty', title: 'Tahitian', originalTitle: 'Reo Tahiti'},
    {key: 'ug', title: 'Uighur', originalTitle: 'Uyƣurqə, ئۇيغۇرچە‎'},
    {key: 'uk', title: 'Ukrainian', originalTitle: 'українська'},
    {key: 'ur', title: 'Urdu', originalTitle: 'اردو'},
    {key: 'uz', title: 'Uzbek', originalTitle: 'zbek, Ўзбек, أۇزبېك‎'},
    {key: 've', title: 'Venda', originalTitle: 'Tshivenḓa'},
    {key: 'vi', title: 'Viettitlese', originalTitle: 'Tiếng Việt'},
    {key: 'vo', title: 'Volapük', originalTitle: 'Volapük'},
    {key: 'wa', title: 'Walloon', originalTitle: 'Walon'},
    {key: 'cy', title: 'Welsh', originalTitle: 'Cymraeg'},
    {key: 'wo', title: 'Wolof', originalTitle: 'Wollof'},
    {key: 'fy', title: 'Western Frisian', originalTitle: 'Frysk'},
    {key: 'xh', title: 'Xhosa', originalTitle: 'isiXhosa'},
    {key: 'yi', title: 'Yiddish', originalTitle: 'ייִדיש'},
    {key: 'yo', title: 'Yoruba', originalTitle: 'Yorùbá'},
    {key: 'za', title: 'Zhuang', originalTitle: 'Saɯ cueŋƅ, Saw cuengh'},
  ];