export default [
    {key: 'acrobatics', title: 'Acrobatics', icon: '🤸'},
    {key: 'archery', title: 'Archery', icon: '🏹'},
    {key: 'badminton', title: 'Badminton', icon: '🏸'},
    {key: 'baseball', title: 'Baseball', icon: '⚾'},
    {key: 'basketball', title: 'Basketball', icon: '🏀'},
    {key: 'bmx', title: 'Bicycle Motocross', icon: '🚴‍♂️'},
    {key: 'billiards', title: 'Billiards/Pool', icon: '🎱'},
    {key: 'bodybuilding', title: 'Bodybuilding', icon: '🏋️‍♂️'},
    {key: 'bowling', title: 'Bowling', icon: '🎳'},
    {key: 'boxing', title: 'Boxing', icon: '🥊'},
    {key: 'canoeing', title: 'Canoeing', icon: '🛶'},
    {key: 'car_racing', title: 'Car Racing', icon: '🏎️'},
    {key: 'cheerleading', title: 'Cheerleading', icon: '📣'},
    {key: 'chess', title: 'Chess', icon: '♟️'},
    {key: 'climbing', title: 'Climbing', icon: '🧗‍♂️'},
    {key: 'cricket', title: 'Cricket', icon: '🏏'},
    {key: 'croquet', title: 'Croquet', icon: '🔨'},
    {key: 'curling', title: 'Curling', icon: '🥌'},
    {key: 'dance', title: 'Dance', icon: '💃'},
    {key: 'darts', title: 'Darts', icon: '🎯'},
    {key: 'dodgeball', title: 'Dodgeball', icon: '🤾‍♂️'},
    {key: 'fencing', title: 'Fencing', icon: '🤺'},
    {key: 'figure_skating', title: 'Figure Skating', icon: '⛸️'},
    {key: 'football', title: 'Football/Soccer', icon: '⚽'},
    {key: 'frisbee', title: 'Frisbee', icon: '🥏'},
    {key: 'golf', title: 'Golf', icon: '⛳'},
    {key: 'gymnastics', title: 'Gymnastics', icon: '🤸‍♂️'},
    {key: 'handball', title: 'Handball', icon: '🤾'},
    {key: 'hockey', title: 'Hockey', icon: '🏑'},
    {key: 'horse_racing', title: 'Horse Racing', icon: '🏇'},
    {key: 'ice_hockey', title: 'Ice Hockey', icon: '🏒'},
    {key: 'ice_skating', title: 'Ice Skating', icon: '⛸️'},
    {key: 'jet_ski_racing', title: 'Jet Ski Racing', icon: '🚤'},
    {key: 'judo', title: 'Judo', icon: '🥋'},
    {key: 'karate', title: 'Karate', icon: '🥋'},
    {key: 'kayaking', title: 'Kayaking', icon: '🛶'},
    {key: 'kick_boxing', title: 'Kick Boxing', icon: '🥊'},
    {key: 'kite_surfing', title: 'Kite Surfing', icon: '🪁'},
    {key: 'lacrosse', title: 'Lacrosse', icon: '🥍'},
    {key: 'luge', title: 'Luge', icon: '🛷'},
    {key: 'mma', title: 'Mixed Martial Arts', icon: '🥊'},
    {key: 'motocross', title: 'Motocross', icon: '🏍️'},
    {key: 'muay_thai', title: 'Muay Thai', icon: '🥊'},
    {key: 'padel', title: 'Padel', icon: '🎾'},
    {key: 'paddle', title: 'Paddle', icon: '🛶'},
    {key: 'paintball', title: 'Paintball', icon: '🔫'},
    {key: 'parachuting', title: 'Parachuting', icon: '🪂'},
    {key: 'paragliding', title: 'Paragliding', icon: '🪂'},
    {key: 'parkour', title: 'Parkour', icon: '🏃‍♂️'},
    {key: 'polo', title: 'Polo', icon: '🏇'},
    {key: 'pool', title: 'Pool/Billiards', icon: '🎱'},
    {key: 'powerlifting', title: 'Powerlifting', icon: '🏋️‍♂️'},
    {key: 'rafting', title: 'Rafting', icon: '🚣‍♂️'},
    {key: 'rhythmic_gymnastics', title: 'Rhythmic Gymnastics', icon: '🤸‍♀️'},
    {key: 'rock_climbing', title: 'Rock Climbing', icon: '🧗‍♂️'},
    {key: 'rowing', title: 'Rowing', icon: '🚣'},
    {key: 'rugby', title: 'Rugby', icon: '🏉'},
    {key: 'running', title: 'Running', icon: '🏃'},
    {key: 'sailing', title: 'Sailing', icon: '⛵'},
    {key: 'sandboarding', title: 'Sandboarding', icon: '🏂'},
    {key: 'scuba_diving', title: 'Scuba Diving', icon: '🤿'},
    {key: 'shooting', title: 'Shooting', icon: '🔫'},
    {key: 'skateboarding', title: 'Skateboarding', icon: '🛹'},
    {key: 'skiing', title: 'Skiing', icon: '⛷️'},
    {key: 'snowboarding', title: 'Snowboarding', icon: '🏂'},
    {key: 'softball', title: 'Softball', icon: '⚾'},
    {key: 'spikeball', title: 'Spikeball', icon: '🏐'},
    {key: 'squash', title: 'Squash', icon: '🎾'},
    {key: 'surfing', title: 'Surfing', icon: '🏄‍♂️'},
    {key: 'swimming', title: 'Swimming', icon: '🏊‍♂️'},
    {key: 'synchronized_swimming', title: 'Synchronized Swimming', icon: '🏊‍♀️'},
    {key: 'table_tennis', title: 'Table Tennis', icon: '🏓'},
    {key: 'taekwondo', title: 'Taekwondo', icon: '🥋'},
    {key: 'tennis', title: 'Tennis', icon: '🎾'},
    {key: 'track_and_field', title: 'Track and Field', icon: '🏃‍♂️'},
    {key: 'trampolining', title: 'Trampolining', icon: '🤸‍♂️'},
    {key: 'triathlon', title: 'Triathlon (Tetrathlon, etc.)', icon: '🏊‍♂️🚴‍♂️🏃‍♂️'},
    {key: 'volleyball', title: 'Volleyball', icon: '🏐'},
    {key: 'diving', title: 'Diving', icon: '🤿'},
    {key: 'water_polo', title: 'Water Polo', icon: '🤽‍♂️'},
    {key: 'weightlifting', title: 'Weightlifting', icon: '🏋️‍♂️'},
    {key: 'windsurfing', title: 'Windsurfing', icon: '🏄‍♂️'},
  ];
  