export default [
    {key: 'acrobatics', title: 'Acrobaties', icon: '🤸'},
    {key: 'archery', title: 'Tir à l\'arc', icon: '🏹'},
    {key: 'badminton', title: 'Badminton', icon: '🏸'},
    {key: 'baseball', title: 'Base-ball', icon: '⚾'},
    {key: 'basketball', title: 'Basket-ball', icon: '🏀'},
    {key: 'bmx', title: 'BMX', icon: '🚴‍♂️'},
    {key: 'billiards', title: 'Billard', icon: '🎱'},
    {key: 'bodybuilding', title: 'Culturisme', icon: '🏋️‍♂️'},
    {key: 'bowling', title: 'Bowling', icon: '🎳'},
    {key: 'boxing', title: 'Boxe', icon: '🥊'},
    {key: 'canoeing', title: 'Canoë-kayak', icon: '🛶'},
    {key: 'car_racing', title: 'Course automobile', icon: '🏎️'},
    {key: 'cheerleading', title: 'Pom-pom girl', icon: '📣'},
    {key: 'chess', title: 'Échecs', icon: '♟️'},
    {key: 'climbing', title: 'Escalade', icon: '🧗‍♂️'},
    {key: 'cricket', title: 'Cricket', icon: '🏏'},
    {key: 'croquet', title: 'Croquet', icon: '🔨'},
    {key: 'curling', title: 'Curling', icon: '🥌'},
    {key: 'dance', title: 'Danse', icon: '💃'},
    {key: 'darts', title: 'Fléchettes', icon: '🎯'},
    {key: 'diving', title: 'Plongeon', icon: '🤿'},
    {key: 'dodgeball', title: 'Ballon prisonnier', icon: '🤾‍♂️'},
    {key: 'fencing', title: 'Escrime', icon: '🤺'},
    {key: 'figure_skating', title: 'Patinage artistique', icon: '⛸️'},
    {key: 'football', title: 'Football', icon: '⚽'},
    {key: 'frisbee', title: 'Frisbee', icon: '🥏'},
    {key: 'golf', title: 'Golf', icon: '⛳'},
    {key: 'gymnastics', title: 'Gymnastique', icon: '🤸‍♂️'},
    {key: 'handball', title: 'Handball', icon: '🤾'},
    {key: 'hockey', title: 'Hockey', icon: '🏑'},
    {key: 'horse_racing', title: 'Course hippique', icon: '🏇'},
    {key: 'ice_hockey', title: 'Hockey sur glace', icon: '🏒'},
    {key: 'ice_skating', title: 'Patinage sur glace', icon: '⛸️'},
    {key: 'jet_ski_racing', title: 'Course de jet-ski', icon: '🚤'},
    {key: 'judo', title: 'Judo', icon: '🥋'},
    {key: 'karate', title: 'Karaté', icon: '🥋'},
    {key: 'kayaking', title: 'Kayak', icon: '🛶'},
    {key: 'kick_boxing', title: 'Kick-boxing', icon: '🥊'},
    {key: 'kite_surfing', title: 'Kitesurf', icon: '🪁'},
    {key: 'lacrosse', title: 'Crosse', icon: '🥍'},
    {key: 'luge', title: 'Luge', icon: '🛷'},
    {key: 'mma', title: 'Arts martiaux mixtes', icon: '🥊'},
    {key: 'motocross', title: 'Motocross', icon: '🏍️'},
    {key: 'muay_thai', title: 'Muay-thaï', icon: '🥊'},
    {key: 'padel', title: 'Padel', icon: '🎾'},
    {key: 'paddle', title: 'Paddle', icon: '🛶'},
    {key: 'paintball', title: 'Paintball', icon: '🔫'},
    {key: 'parachuting', title: 'Parachutisme', icon: '🪂'},
    {key: 'paragliding', title: 'Parapente', icon: '🪂'},
    {key: 'parkour', title: 'Parkour', icon: '🏃‍♂️'},
    {key: 'polo', title: 'Polo', icon: '🏇'},
    {key: 'pool', title: 'Billard', icon: '🎱'},
    {key: 'powerlifting', title: 'Force athlétique', icon: '🏋️‍♂️'},
    {key: 'rafting', title: 'Rafting', icon: '🚣‍♂️'},
    {key: 'rhythmic_gymnastics', title: 'Gymnastique rythmique', icon: '🤸‍♀️'},
    {key: 'rock_climbing', title: 'Escalade', icon: '🧗‍♂️'},
    {key: 'rowing', title: 'Aviron', icon: '🚣'},
    {key: 'rugby', title: 'Rugby', icon: '🏉'},
    {key: 'running', title: 'Course à pied', icon: '🏃'},
    {key: 'sailing', title: 'Voile', icon: '⛵'},
    {key: 'sandboarding', title: 'Sandboard', icon: '🏂'},
    {key: 'scuba_diving', title: 'Plongée sous-marine', icon: '🤿'},
    {key: 'shooting', title: 'Tir', icon: '🔫'},
    {key: 'skateboarding', title: 'Skateboard', icon: '🛹'},
    {key: 'skiing', title: 'Ski', icon: '⛷️'},
    {key: 'snowboarding', title: 'Snowboard', icon: '🏂'},
    {key: 'softball', title: 'Softball', icon: '⚾'},
    {key: 'spikeball', title: 'Spikeball', icon: '🏐'},
    {key: 'squash', title: 'Squash', icon: '🎾'},
    {key: 'surfing', title: 'Surf', icon: '🏄‍♂️'},
    {key: 'swimming', title: 'Natation', icon: '🏊‍♂️'},
    {key: 'synchronized_swimming', title: 'Natation synchronisée', icon: '🏊‍♀️'},
    {key: 'table_tennis', title: 'Tennis de table', icon: '🏓'},
    {key: 'taekwondo', title: 'Taekwondo', icon: '🥋'},
    {key: 'tennis', title: 'Tennis', icon: '🎾'},
    {key: 'track_and_field', title: 'Athlétisme', icon: '🏃‍♂️'},
    {key: 'trampolining', title: 'Trampoline', icon: '🤸‍♂️'},
    {key: 'triathlon', title: 'Triathlon', icon: '🏊‍♂️🚴‍♂️🏃‍♂️'},
    {key: 'volleyball', title: 'Volley-ball', icon: '🏐'},
    {key: 'water_polo', title: 'Water-polo', icon: '🤽‍♂️'},
    {key: 'weightlifting', title: 'Haltérophilie', icon: '🏋️‍♂️'},
    {key: 'windsurfing', title: 'Planche à voile', icon: '🏄‍♂️'},
  ];